# Generated by Django 5.2.6 on 2025-09-16 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='anilist_access_token',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
