# Generated by Django 5.2.6 on 2025-09-16 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_profile_anilist_access_token'),
    ]

    operations = [
        migrations.RenameField(
            model_name='media',
            old_name='title',
            new_name='primary_title',
        ),
        migrations.AddField(
            model_name='media',
            name='secondary_title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
