# Generated by Django 5.2.6 on 2025-09-20 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_rename_title_media_primary_title_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermedia',
            name='score',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
