# Generated by Django 5.2.6 on 2025-09-21 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_usermedia_score'),
    ]

    operations = [
        migrations.AlterField(
            model_name='media',
            name='media_type',
            field=models.CharField(choices=[('ANIME', 'Anime'), ('MOVIE', 'Movie'), ('BOOK', 'Book'), ('GAME', 'Game'), ('TV', 'TV Show')], max_length=7),
        ),
    ]
