# Generated by Django 5.2.6 on 2025-09-22 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_media_media_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='tmdb_account_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='tmdb_session_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
