# Generated by Django 5.2.6 on 2025-09-22 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_tmdbrequesttoken'),
    ]

    operations = [
        migrations.AlterField(
            model_name='media',
            name='tmdb_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='media',
            unique_together={('tmdb_id', 'media_type')},
        ),
    ]
