# Generated by Django 5.2.6 on 2025-09-22 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_alter_media_tmdb_id_alter_media_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='media',
            name='rawg_id',
            field=models.IntegerField(blank=True, null=True, unique=True),
        ),
    ]
