# Generated by Django 5.2.6 on 2025-09-22 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_media_rawg_id'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='media',
            unique_together={('tmdb_id', 'media_type')},
        ),
        migrations.AddField(
            model_name='media',
            name='google_book_id',
            field=models.CharField(blank=True, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='media',
            name='media_type',
            field=models.CharField(choices=[('ANIME', 'Anime'), ('MOVIE', 'Movie'), ('BOOK', 'Book'), ('GAME', 'Game'), ('TV', 'TV Show'), ('MANGA', 'Manga')], max_length=7),
        ),
        migrations.AlterUniqueTogether(
            name='media',
            unique_together={('google_book_id', 'media_type'), ('tmdb_id', 'media_type')},
        ),
    ]
