# Generated by Django 5.2.6 on 2025-09-23 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_media_rawg_id'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='media',
            unique_together={('tmdb_id', 'media_type')},
        ),
        migrations.AddField(
            model_name='media',
            name='google_book_id',
            field=models.CharField(blank=True, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='media',
            name='length',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='media',
            name='media_type',
            field=models.CharField(choices=[('ANIME', 'Anime'), ('MOVIE', 'Movie'), ('BOOK', 'Book'), ('GAME', 'Game'), ('TV_SHOW', 'TV Show'), ('MANGA', 'Manga')], max_length=7),
        ),
        migrations.AlterField(
            model_name='usermedia',
            name='status',
            field=models.CharField(blank=True, choices=[('IN_PROGRESS', 'In Progress'), ('COMPLETED', 'Completed'), ('PAUSED', 'Paused'), ('DROPPED', 'Dropped'), ('PLANNED', 'Planned')], max_length=11, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='media',
            unique_together={('google_book_id', 'media_type'), ('tmdb_id', 'media_type')},
        ),
    ]
