# Generated by Django 5.2.6 on 2025-09-23 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_alter_media_unique_together_media_google_book_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='media',
            name='mal_id',
            field=models.IntegerField(blank=True, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='mal_access_token',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='mal_refresh_token',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='mal_username',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
