# Generated by Django 5.2.6 on 2025-09-22 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_alter_media_unique_together_media_google_book_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermedia',
            name='status',
            field=models.CharField(blank=True, choices=[('IN_PROGRESS', 'In Progress'), ('COMPLETED', 'Completed'), ('PAUSED', 'Paused'), ('DROPPED', 'Dropped'), ('PLANNED', 'Planned')], max_length=11, null=True),
        ),
    ]
