# Generated by Django 5.2.6 on 2025-09-23 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_alter_usermedia_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='media',
            name='media_type',
            field=models.CharField(choices=[('ANIME', 'Anime'), ('MOVIE', 'Movie'), ('BOOK', 'Book'), ('GAME', 'Game'), ('TV_SHOW', 'TV Show'), ('MANGA', 'Manga')], max_length=7),
        ),
    ]
