# Generated by Django 5.2.6 on 2025-09-24 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_malauthrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='media',
            name='keep_local_on_sync',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='media',
            name='keep_user_login',
            field=models.BooleanField(default=True),
        ),
    ]
