# Generated by Django 5.2.6 on 2025-09-24 07:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_media_keep_local_on_sync_media_keep_user_login'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='media',
            name='keep_local_on_sync',
        ),
        migrations.RemoveField(
            model_name='media',
            name='keep_user_login',
        ),
    ]
