# Generated by Django 5.2.6 on 2025-09-24 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_remove_media_keep_local_on_sync_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='keep_local_on_sync',
            field=models.BooleanField(default=True),
        ),
    ]
