# Generated by Django 5.2.6 on 2025-09-24 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_profile_keep_local_on_sync'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='dark_mode',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='keep_user_logged_in',
            field=models.BooleanField(default=True),
        ),
    ]
