# Generated by Django 5.2.6 on 2025-09-25 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_customlist_customlistentry'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='steam_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='steam_username',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
