# Generated by Django 5.2.6 on 2025-09-26 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_profile_steam_id_profile_steam_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='media',
            name='steam_appid',
            field=models.IntegerField(blank=True, null=True, unique=True),
        ),
    ]
