# Generated by Django 5.2.6 on 2025-09-29 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_media_steam_appid'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='use_steam_or_rawg',
            field=models.BooleanField(default=True),
        ),
    ]
